// Auto-generated entity names from the scene


/**
 * Object containing all entity names in the scene for autocomplete support.
 */
export enum EntityNames {
  Bird_Fountain = "Bird Fountain",
  Blue_Bicycle = "Blue Bicycle",
  Blue_Bicycle_2 = "Blue Bicycle_2",
  Clay_Pot = "Clay Pot",
  Clay_Pot_2 = "Clay Pot_2",
  Cube = "Cube",
  Cylinder_3 = "Cylinder_3",
  Cylinder_4 = "Cylinder_4",
  Cylinder_5 = "Cylinder_5",
  Cylinder_6 = "Cylinder_6",
  Cylinder_7 = "Cylinder_7",
  Ground = "Ground",
  Ornamental_Fountain = "Ornamental Fountain",
  Outdoor_Chair = "Outdoor Chair",
  Outdoor_Chair_2 = "Outdoor Chair_2",
  Outdoor_Chair_3 = "Outdoor Chair_3",
  Outdoor_Chair_4 = "Outdoor Chair_4",
  Outdoor_Chair_5 = "Outdoor Chair_5",
  Outdoor_Chair_6 = "Outdoor Chair_6",
  Outdoor_Chair_7 = "Outdoor Chair_7",
  Outdoor_Chair_8 = "Outdoor Chair_8",
  Planted_Fern = "Planted Fern",
  Planted_Fern_2 = "Planted Fern_2",
  Planted_Fern_3 = "Planted Fern_3",
  Planted_Fern_4 = "Planted Fern_4",
  The_Lonely_Fountain = "The Lonely Fountain",
  Tile_1 = "Tile 1",
  Tile_10 = "Tile 10",
  Tile_11 = "Tile 11",
  Tile_12 = "Tile 12",
  Tile_13 = "Tile 13",
  Tile_14 = "Tile 14",
  Tile_15 = "Tile 15",
  Tile_16 = "Tile 16",
  Tile_17 = "Tile 17",
  Tile_18 = "Tile 18",
  Tile_19 = "Tile 19",
  Tile_2 = "Tile 2",
  Tile_20 = "Tile 20",
  Tile_21 = "Tile 21",
  Tile_22 = "Tile 22",
  Tile_23 = "Tile 23",
  Tile_24 = "Tile 24",
  Tile_25 = "Tile 25",
  Tile_3 = "Tile 3",
  Tile_4 = "Tile 4",
  Tile_5 = "Tile 5",
  Tile_6 = "Tile 6",
  Tile_7 = "Tile 7",
  Tile_8 = "Tile 8",
  Tile_9 = "Tile 9",
  Traditional_Lamp_Post = "Traditional Lamp Post",
  Traditional_Lamp_Post_2 = "Traditional Lamp Post_2",
  Traditional_Lamp_Post_3 = "Traditional Lamp Post_3",
  Traditional_Lamp_Post_4 = "Traditional Lamp Post_4",
  Umbrella_Table_2 = "Umbrella Table_2",
  Umbrella_Table_3 = "Umbrella Table_3",
  venice_cityscene_main_without_props_scaled_001_glb = "venice_cityscene_main_without_props_scaled_001.glb",
} 
